name: 🐛 Bug Report
description: File a bug report to help us improve Mercury
title: "[Bug]: "
labels: ["bug", "status: todo"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 🙏
        
        Please provide as much detail as possible to help us reproduce and fix the issue.

  - type: input
    id: mercury-version
    attributes:
      label: Mercury Version
      description: Run `mercury --version` in terminal
      placeholder: "0.1.0-beta"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: Which OS are you using?
      options:
        - macOS (Intel)
        - macOS (Apple Silicon)
        - Linux
        - Windows
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug clearly
      placeholder: "When I click File → Import → Postman, Mercury crashes with error..."
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: "I expected the Postman collection to import successfully"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the issue
      placeholder: |
        1. Open Mercury
        2. Click File → Import → Postman
        3. Select collection.json file
        4. App crashes
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Messages / Logs
      description: Copy any error messages or crash logs
      placeholder: "Paste error messages here..."
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information that might help (screenshots, sample files, etc.)
      placeholder: "Add any other context about the problem here"

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: This is a bug in Mercury (not a feature request)
          required: true
        - label: I agree to follow the [Code of Conduct](../CODE_OF_CONDUCT.md)
          required: true
